SELECT churned_date,
       CASE WHEN is_churned = TRUE THEN 1 ELSE 0 END as is_churned,
       CASE WHEN language = 'DE' THEN 1 ELSE 0 END as language_DE,
       CASE WHEN language = 'EN' THEN 1 ELSE 0 END as language_EN,
       CASE WHEN language = 'FR' THEN 1 ELSE 0 END as language_FR,
       CASE WHEN language = 'IT' THEN 1 ELSE 0 END as language_IT,
       CASE WHEN gender = 'D' THEN 1 ELSE 0 END as gender_D,
       CASE WHEN gender = 'F' THEN 1 ELSE 0 END as gender_F,
       CASE WHEN gender = 'M' THEN 1 ELSE 0 END as gender_M,
       CASE WHEN age >=  0 and age < 25 THEN 1 ELSE 0 END as age_0_25,
       CASE WHEN age >= 25 and age < 50 THEN 1 ELSE 0 END as age_25_50,
       CASE WHEN age >= 50 and age < 75 THEN 1 ELSE 0 END as age_50_75,
       CASE WHEN age >= 75 THEN 1 ELSE 0 END as age_75,
       CASE WHEN tenure >=   0 and tenure < 100 THEN 1 ELSE 0 END as tenure_0_100,
       CASE WHEN tenure >= 100 and tenure < 200 THEN 1 ELSE 0 END as tenure_100_200,
       CASE WHEN tenure >= 200 and tenure < 300 THEN 1 ELSE 0 END as tenure_200_300,
       CASE WHEN tenure >= 300 and tenure < 400 THEN 1 ELSE 0 END as tenure_300_400,
       CASE WHEN tenure >= 400 THEN 1 ELSE 0 END as tenure_400,
       CASE WHEN has_call = TRUE THEN 1 ELSE 0 END as has_call,
       CASE WHEN call_reason IS NULL THEN -1 WHEN call_reason = 'Billing' THEN 1 ELSE 0 END as call_reason_billing,
       CASE WHEN call_reason IS NULL THEN -1 WHEN call_reason = 'Churn' THEN 1 ELSE 0 END as call_reason_churn,
       CASE WHEN call_reason IS NULL THEN -1 WHEN call_reason = 'Product' THEN 1 ELSE 0 END as call_reason_product,
       CASE WHEN call_reason IS NULL THEN -1 WHEN call_reason = 'Technical' THEN 1 ELSE 0 END as call_reason_technical,
       CASE WHEN time_in_queue IS NULL THEN -1 WHEN time_in_queue >= 0 and time_in_queue < 20 THEN 1 ELSE 0 END as time_in_queue_0_20,
       CASE WHEN time_in_queue IS NULL THEN -1 WHEN time_in_queue >= 20 and time_in_queue < 40 THEN 1 ELSE 0 END as time_in_queue_20_40,
       CASE WHEN time_in_queue IS NULL THEN -1 WHEN time_in_queue >= 40 THEN 1 ELSE 0 END as time_in_queue_40,
       CASE WHEN handling_time_s IS NULL THEN -1 WHEN handling_time_s >= 0 and handling_time_s < 40 THEN 1 ELSE 0 END as handling_time_s_0_40,
       CASE WHEN handling_time_s IS NULL THEN -1 WHEN handling_time_s >= 40 and handling_time_s < 80 THEN 1 ELSE 0 END as handling_time_s_40_80,
       CASE WHEN handling_time_s IS NULL THEN -1 WHEN handling_time_s >= 80 THEN 1 ELSE 0 END as handling_time_s_80,
       CASE WHEN customer_satisfaction_after_call IS NULL THEN -1 WHEN customer_satisfaction_after_call = 1 THEN 1 ELSE 0 END as customer_satisfaction_after_call_1,
       CASE WHEN customer_satisfaction_after_call IS NULL THEN -1 WHEN customer_satisfaction_after_call = 2 THEN 1 ELSE 0 END as customer_satisfaction_after_call_2,
       CASE WHEN customer_satisfaction_after_call IS NULL THEN -1 WHEN customer_satisfaction_after_call = 3 THEN 1 ELSE 0 END as customer_satisfaction_after_call_3,
       CASE WHEN customer_satisfaction_after_call IS NULL THEN -1 WHEN customer_satisfaction_after_call = 4 THEN 1 ELSE 0 END as customer_satisfaction_after_call_4,
       CASE WHEN customer_satisfaction_after_call IS NULL THEN -1 WHEN customer_satisfaction_after_call = 5 THEN 1 ELSE 0 END as customer_satisfaction_after_call_5
  FROM {{ ref('account_interactions') }} 

